ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "preferredPrayerDate" TIMESTAMP(3);
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "honouredPersonImage" TEXT;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "specialPrayerMessage" TEXT;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "wishToVisitHome" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "preferredVisitDate" TIMESTAMP(3);

ALTER TABLE "FollowUp" ADD COLUMN IF NOT EXISTS "clientInterest" TEXT;
ALTER TABLE "FollowUp" ADD COLUMN IF NOT EXISTS "readyToPayAmount" DOUBLE PRECISION;
ALTER TABLE "FollowUp" ADD COLUMN IF NOT EXISTS "paymentMode" TEXT;
ALTER TABLE "FollowUp" ADD COLUMN IF NOT EXISTS "nextFollowupStatus" TEXT;
